DROP TABLE IF EXISTS prodImages;
DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS bids;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users;



-- Empty Data
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE prodImages;
TRUNCATE TABLE answers;
TRUNCATE TABLE questions;
TRUNCATE TABLE bids;
TRUNCATE TABLE products;
TRUNCATE TABLE users;
SET FOREIGN_KEY_CHECKS = 1;